name: Build SwiftlyGo Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: golang:1.24.0-alpine
    steps:
      - name: Install git
        run: apk add --no-cache git
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build SwiftlyGo
        run: |
          cd source
          GOOS=linux GOARCH=amd64 go build -buildvcs=false -ldflags="-s -w" -o swiftlygo-x86_64
          GOOS=linux GOARCH=arm64 go build -buildvcs=false -ldflags="-s -w" -o swiftlygo-aarch64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: swiftlygo-binarys
          path: |
            source/swiftlygo-x86_64
            source/swiftlygo-aarch64
            source/create-env.sh
        