name: Build SwiftlyGo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.10

      - name: Build SwiftlyGo
        run: |
          cd source
          go build -o swiftlygo
          bash ./create-env.sh

      - name: Verify build
        run: |
          cd source
          ./swiftlygo -h
          sudo ./swiftlygo list
